
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class C_
{

    public int SNO { get; set; }

    public string TRAN_ID { get; set; }

    public string FARM_CODE { get; set; }

    public string ORGN_CODE { get; set; }

    public string PURCH_REF { get; set; }

    public double LOAN_AMOUNT { get; set; }

    public double PURCH_AMOUNT { get; set; }

    public double BALANCE_AMOUNT { get; set; }

    public string REMARKS { get; set; }

    public string STATUS { get; set; }

    public string FLAG { get; set; }

    public string CREATED_BY { get; set; }

    public System.DateTime CREATED_DATE { get; set; }

    public string LAST_UPDATED_BY { get; set; }

    public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }

    public byte[] LASTUPDATE { get; set; }

}

}
