
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GPIL_LOG
{

    public string proceName { get; set; }

    public System.DateTime TimeOfError { get; set; }

    public string error_msg { get; set; }

    public string @params { get; set; }

}

}
