
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    

    public partial class GPIL_RATE_MASTER
    {
        [Required(ErrorMessage = "Location Code is required")]
        public string Loc_Code { get; set; }
        [Required(ErrorMessage = "Item Code is required")]
        public string Item_Code { get; set; }
        [Required(ErrorMessage = "Status is required")]
        public decimal Rate { get; set; }

    public DateTime Last_Updated_Date { get; set; }

    public int ID { get; set; }

}
    public class ListRateMaster
    {
        public List<GPIL_RATE_MASTER> RateMasters { get; set; }
    }
}
