
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GPIL_OPERATION_RECIPE
    {

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GPIL_OPERATION_RECIPE()
    {

        this.GPIL_CLASSIFICATION_HDR = new HashSet<GPIL_CLASSIFICATION_HDR>();

        this.GPIL_CLASSIFICATION_HDR_TEMP = new HashSet<GPIL_CLASSIFICATION_HDR_TEMP>();

        this.GPIL_CLASSIFY_SUFFIX = new HashSet<GPIL_CLASSIFY_SUFFIX>();

        this.GPIL_CLASSIFY_SUFFIX1 = new HashSet<GPIL_CLASSIFY_SUFFIX>();

        this.GPIL_CROP_TRANS_HDR = new HashSet<GPIL_CROP_TRANS_HDR>();

        this.GPIL_CROP_TRANS_HDR_TEMP = new HashSet<GPIL_CROP_TRANS_HDR_TEMP>();

        this.GPIL_GRADING_HDR = new HashSet<GPIL_GRADING_HDR>();

        this.GPIL_GRADING_HDR_TEMP = new HashSet<GPIL_GRADING_HDR_TEMP>();

        this.GPIL_THRESH_RECON_HDR = new HashSet<GPIL_THRESH_RECON_HDR>();

        this.GPIL_THRESH_RECON_HDR_TEMP = new HashSet<GPIL_THRESH_RECON_HDR_TEMP>();

    }


        //public int SNO { get; set; }

        //public string RECIPE_CODE { get; set; }

        //public string OPERATION_RECIPE { get; set; }

        //public string CREATED_BY { get; set; }

        //public System.DateTime CREATED_DATE { get; set; }

        //public string LAST_UPDATED_BY { get; set; }

        //public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }

        //public string STATUS { get; set; }

        //public string FLAG { get; set; }

        //public byte[] LASTUPDATE { get; set; }

        //public string ATTRIBUTE1 { get; set; }

        //public string ATTRIBUTE2 { get; set; }

        //public string ATTRIBUTE3 { get; set; }

        //public string ATTRIBUTE4 { get; set; }

        //public string ATTRIBUTE5 { get; set; }
        public int SNO { get; set; }
        [Required(ErrorMessage = "RECIPE_CODE IS REQUIRED")]
        public string RECIPE_CODE { get; set; }
        [Required(ErrorMessage = "OPERATION_RECIPE IS REQUIRED")]
        public string OPERATION_RECIPE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        [Required(ErrorMessage = "STATUS IS REQUIRED")]
        public string STATUS { get; set; }
        public string FLAG { get; set; }
        public byte[] LASTUPDATE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_CLASSIFICATION_HDR> GPIL_CLASSIFICATION_HDR { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_CLASSIFICATION_HDR_TEMP> GPIL_CLASSIFICATION_HDR_TEMP { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_CLASSIFY_SUFFIX> GPIL_CLASSIFY_SUFFIX { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_CLASSIFY_SUFFIX> GPIL_CLASSIFY_SUFFIX1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_CROP_TRANS_HDR> GPIL_CROP_TRANS_HDR { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_CROP_TRANS_HDR_TEMP> GPIL_CROP_TRANS_HDR_TEMP { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_GRADING_HDR> GPIL_GRADING_HDR { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_GRADING_HDR_TEMP> GPIL_GRADING_HDR_TEMP { get; set; }

    public virtual GPIL_USER_MASTER GPIL_USER_MASTER { get; set; }

    public virtual GPIL_USER_MASTER GPIL_USER_MASTER1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_THRESH_RECON_HDR> GPIL_THRESH_RECON_HDR { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GPIL_THRESH_RECON_HDR_TEMP> GPIL_THRESH_RECON_HDR_TEMP { get; set; }

}
    public class ListOperationRecipe
    {
        public List<GPIL_OPERATION_RECIPE> OperationRecipe { get; set; }
    }
}
