
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class mJobType
{

    public int SNo { get; set; }

    public string JobType { get; set; }

    public System.Guid rowguid { get; set; }

    public byte[] LASTUPDATE { get; set; }

}

}
