
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class mRate
{

    public string LocCode { get; set; }

    public string GradeCode { get; set; }

    public string GradeName { get; set; }

    public string Rate { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public System.Guid rowguid { get; set; }

    public byte[] LASTUPDATE { get; set; }

}

}
