
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class mTransporter
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public mTransporter()
    {

        this.tDispatchDetails = new HashSet<tDispatchDetail>();

    }


    public string TransporterCode { get; set; }

    public string TransporterName { get; set; }

    public string Destination { get; set; }

    public string Amount { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public System.Guid rowguid { get; set; }

    public byte[] LASTUPDATE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tDispatchDetail> tDispatchDetails { get; set; }

}

}
