
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class mUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public mUser()
    {

        this.tDispatchNotes = new HashSet<tDispatchNote>();

    }


    public string LocCode { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public Nullable<bool> UserType { get; set; }

    public string JobType { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<bool> Masters { get; set; }

    public Nullable<bool> Transactions { get; set; }

    public Nullable<bool> Reports { get; set; }

    public Nullable<bool> DataSync { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public System.Guid rowguid { get; set; }

    public byte[] LASTUPDATE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tDispatchNote> tDispatchNotes { get; set; }

}

}
