
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPILWebApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class mWebSetting
{

    public string FactoryCode { get; set; }

    public bool ERP { get; set; }

    public bool WMS { get; set; }

    public string ERPBasedOn { get; set; }

    public string ERPOrgCode { get; set; }

    public string ERPAcctCode { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public System.Guid rowguid { get; set; }

}

}
