using CrystalDecisions.CrystalReports.Engine;
using GPILWebApp.Models;
using GPILWebApp.ViewModel;
using GPILWebApp.ViewModel.GLT;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace GPILWebApp.CrystalReport.WebForms
{
    public partial class WeeklyReconcilation : System.Web.UI.Page
    {
        GLTManagement GLTMgt = new GLTManagement();
        ReportDocument CustomerReport = new ReportDocument();
        ReportDocument CustomerReport1 = new ReportDocument();
        CrystalReportData crd = new CrystalReportData();
        LPDManagementt lpdMgt = new LPDManagementt();
        private GREEN_LEAF_TRACEABILITYEntities _context;
        DataTable dtWeekHdr = new DataTable();
        DataTable dtWeekDtl = new DataTable();
        DataTable dt2 = new DataTable();
        public WeeklyReconcilation()
        {
            _context = new GREEN_LEAF_TRACEABILITYEntities();
        }
        protected void Page_Load(object sender, EventArgs e)
        {

            
            if (!IsPostBack)
            {
                bindDropDown();
            }
            viewrpt();
        }
        private void bindDropDown()
        {
            try
            {

                DataSet ds1 = new DataSet();
                ds1 = crd.GetORGN("CROP", "", "");
                ddlCrop.DataSource = ds1.Tables[0];
                ddlCrop.DataTextField = "CROPYEAR";
                ddlCrop.DataValueField = "CROP";
                ddlCrop.DataBind();
                ddlCrop.Items.Insert(0, new ListItem("- Select -", "0"));
                DataSet ds2 = new DataSet();
                ds2 = crd.GetORGN("VARIETY", "", "");
                ddlVariety.DataSource = ds2.Tables[0];
                ddlVariety.DataTextField = "VARIETYNAME";
                ddlVariety.DataValueField = "VARIETY";
                ddlVariety.DataBind();
                ddlVariety.Items.Insert(0, new ListItem("- Select -", "0"));


            }
            catch (Exception ex)
            {

            }
        }
        protected void btnview_Click(object sender, EventArgs e)
        {
            if (validated())
            {
                viewrpt();
            }
        }

        string strsql;
        public void viewrpt()
        {
            try
            {
                //SqlConnection connection = new SqlConnection(ClsConnection.strConnectionString);

                //ClsConnection.dtWeekHdr = null;
                //ClsConnection.dtWeekDtl = null;
                
                strsql = "SELECT * FROM " +
                      "(SELECT * FROM " +
                      "(SELECT '" + ddlCrop.Text + "' AS CROP,'" + ddlVariety.Text + "' AS VARIETY) AS T0, (SELECT COUNT(GPIL_BALE_NUMBER) AS P_TAP_BALES,ROUND(ISNULL(SUM(NET_WT),0),1) AS P_TAP_QTY FROM GPIL_TAP_FARM_PURCHS_DTLS (NOLOCK) D,GPIL_TAP_FARM_PURCHS_HDR (NOLOCK) H WHERE H.HEADER_ID=D.HEADER_ID AND D.REJE_STATUS='OK' AND H.PURCHASE_TYPE='TAP PURCHASE' AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "' AND H.STATUS IN ('N','P')) AS T1, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS P_FRM_BALES,ROUND(ISNULL(SUM(NET_WT),0),1) AS P_FRM_QTY FROM GPIL_TAP_FARM_PURCHS_DTLS (NOLOCK) D,GPIL_TAP_FARM_PURCHS_HDR (NOLOCK) H WHERE H.HEADER_ID=D.HEADER_ID AND D.REJE_STATUS='OK' AND H.PURCHASE_TYPE='SUNDRY PURCHASE' AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "' AND H.STATUS IN ('N','P') ) AS T2, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS P_SUP_BALES,ROUND(ISNULL(SUM(NET_WEIGHT),0),1) AS P_SUP_QTY FROM GPIL_SUPP_PURCHS_DTLS (NOLOCK) D,GPIL_SUPP_PURCHS_HDR (NOLOCK) H WHERE H.HEADER_ID=D.HEADER_ID AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "' AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('N','P')) AS T3, " +
                      "(SELECT COUNT(NEW_BALE_NUMBER) AS O_CRP_BALES_M,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS O_CRP_QTY_M FROM GPIL_CROP_TRANS_DTLS (NOLOCK) D,GPIL_CROP_TRANS_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('N') AND D.NEW_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%') AS T4, " +
                      "(SELECT COUNT(NEW_BALE_NUMBER) AS O_CRP_BALES_T,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS O_CRP_QTY_T FROM GPIL_CROP_TRANS_DTLS_TEMP (NOLOCK) D,GPIL_CROP_TRANS_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C') AND D.NEW_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%') AS T5, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS O_EB_BALES_M,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS O_EB_QTY_M FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('N') AND BALE_TYPE='OPB' AND D.PRODUCT_TYPE='EB') AS T6, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS O_EB_BALES_T,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS O_EB_QTY_T FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('C') AND BALE_TYPE='OPB' AND D.PRODUCT_TYPE='EB') AS T7, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS O_GT_BALES_M,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS O_GT_QTY_M FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('N') AND BALE_TYPE='OPB' AND D.PRODUCT_TYPE='GT') AS T8, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS O_GT_BALES_T,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS O_GT_QTY_T FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('C') AND BALE_TYPE='OPB' AND D.PRODUCT_TYPE='GT') AS T9, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS LOSS_BALES_M,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS LOSS_QTY_M FROM GPIL_GRADING_DTLS (NOLOCK) D,GPIL_GRADING_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('N') AND BALE_TYPE='OPB' AND D.PRODUCT_TYPE='LOSS') AS T10, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS LOSS_BALES_T,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS LOSS_QTY_T FROM GPIL_GRADING_DTLS_TEMP (NOLOCK) D,GPIL_GRADING_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('I','C') AND BALE_TYPE='OPB' AND D.PRODUCT_TYPE='LOSS') AS T11, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS I_TH_BALES_M,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS I_TH_QTY_M FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('N') AND D.BALE_TYPE='IPB' AND D.GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS'))) AS T12, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS I_TH_BALES_T,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS I_TH_QTY_T FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND H.STATUS IN ('C','Y','I') AND D.BALE_TYPE='IPB' AND D.GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS'))) AS T13, " +
                      "(SELECT COUNT(OLD_BALE_NUMBER) AS I_CRP_BALES_M,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS I_CRP_QTY_M FROM GPIL_CROP_TRANS_DTLS (NOLOCK) D,GPIL_CROP_TRANS_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('N') AND D.OLD_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%') AS T14, " +
                      "(SELECT COUNT(OLD_BALE_NUMBER) AS I_CRP_BALES_T,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS I_CRP_QTY_T FROM GPIL_CROP_TRANS_DTLS_TEMP (NOLOCK) D,GPIL_CROP_TRANS_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C') AND D.OLD_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%') AS T15, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS S_TAP_BALES,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS S_TAP_QTY FROM GPIL_STOCK (NOLOCK) WHERE BUYER_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' AND STATUS ='Y' AND CURR_ORGN_CODE IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') AND GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%')  AND GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='C' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%')  AND GPIL_BALE_NUMBER NOT IN  (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND D.PACKED_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND D.PACKED_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%')) AS T16, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS S_UN_BALES,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS S_UN_QTY FROM GPIL_STOCK (NOLOCK) WHERE BUYER_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%'  AND STATUS ='Y' AND CURR_ORGN_CODE NOT IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') AND GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='C' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND D.PACKED_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='C'  AND D.PACKED_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%') AND GRADE IS NULL) AS T17, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS S_CL_BALES,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS S_CL_QTY FROM GPIL_STOCK (NOLOCK) WHERE GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%'  AND STATUS ='Y' AND CURR_ORGN_CODE NOT IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') AND GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='C' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','Y','I') AND D.BALE_TYPE='IPB' AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%')  AND GPIL_BALE_NUMBER NOT IN  (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND D.PACKED_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='C'  AND D.PACKED_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' ) AND GRADE IS NOT NULL) AS T18, " +
                      "(SELECT COUNT(GPIL_BALE_NUMBER) AS S_INT_BALES,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS S_INT_QTY FROM GPIL_STOCK (NOLOCK) WHERE (BUYER_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' OR  GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%')  AND STATUS ='INT' AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='C' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND D.PACKED_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%' )  AND GPIL_BALE_NUMBER NOT IN  (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='C'  AND D.PACKED_GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%')) AS T19) AS FINAL_TBL";

                DataTable dt = new DataTable();
                dt = GLTMgt.GetQueryResult(strsql);

                //SqlCommand command = new SqlCommand(strsql, connection);
                //command.CommandTimeout = 0;
                //SqlDataAdapter adapter = new SqlDataAdapter(command);
                DataTable dtReconciliation = new DataTable("DT_WEEKLY_RECON");
                //adapter.Fill(dtReconciliation);
                CustomerReport.Load(Server.MapPath("~/CrystalReport/RptWeeklyRecon.rpt"));
                CustomerReport.SetDataSource(dt.DefaultView);
               // CustomerReport.SetDatabaseLogon(ClsConnection.USRID, ClsConnection.PASSWORD, ClsConnection.SERVERIP, ClsConnection.DBNAME);
                CrystalReportViewer1.ReportSource = CustomerReport;
                CrystalReportViewer1.DataBind();

               // ClsConnection.dtWeekHdr = dtReconciliation;


               

                strsql = "SELECT TBL1.ORGN_CODE,TBL1.GRADE,ISNULL(TBL2.S_TAP_BALES,0) AS S_TAP_BALES,ISNULL(TBL2.S_TAP_QTY,0) AS S_TAP_QTY,ISNULL(TBL3.S_UN_BALES,0) AS S_UN_BALES,ISNULL(TBL3.S_UN_QTY,0) AS S_UN_QTY,ISNULL(TBL4.S_CL_BALES,0) AS S_CL_BALES,ISNULL(TBL4.S_CL_QTY,0) AS S_CL_QTY,ISNULL(TBL5.S_INT_BALES,0) AS S_INT_BALES,ISNULL(TBL5.S_INT_QTY,0) AS S_INT_QTY FROM " +
                       "(SELECT ORGN_CODE,GRADE FROM (SELECT (CASE WHEN CURR_ORGN_CODE IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') THEN '#TAP' ELSE CURR_ORGN_CODE END) AS ORGN_CODE,(CASE WHEN GRADE IS NULL THEN BUYER_GRADE ELSE GRADE END) AS GRADE FROM GPIL_STOCK (NOLOCK) WHERE CROP='" + ddlCrop.Text + "' AND VARIETY='" + ddlVariety.Text + "' AND STATUS IN ('INT','Y') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "')AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC') AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "')AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "')) AS T1 GROUP BY ORGN_CODE,GRADE) AS TBL1 " +
                       "FULL OUTER JOIN (SELECT '#TAP' AS ORGN_CODE,BUYER_GRADE AS GRADE,COUNT(GPIL_BALE_NUMBER) AS S_TAP_BALES,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS S_TAP_QTY FROM GPIL_STOCK (NOLOCK) WHERE CROP='" + ddlCrop.Text + "' AND VARIETY='" + ddlVariety.Text + "' AND STATUS ='Y' AND CURR_ORGN_CODE IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC') AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') GROUP BY BUYER_GRADE) AS TBL2 ON TBL1.ORGN_CODE=TBL2.ORGN_CODE  AND TBL1.GRADE=TBL2.GRADE " +
                       "FULL OUTER JOIN (SELECT CURR_ORGN_CODE AS ORGN_CODE,BUYER_GRADE AS GRADE,COUNT(GPIL_BALE_NUMBER) AS S_UN_BALES,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS S_UN_QTY FROM GPIL_STOCK (NOLOCK) WHERE CROP='" + ddlCrop.Text + "' AND VARIETY='" + ddlVariety.Text + "' AND STATUS ='Y' AND CURR_ORGN_CODE NOT IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC') AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GRADE IS NULL GROUP BY CURR_ORGN_CODE,BUYER_GRADE) AS TBL3 ON TBL1.ORGN_CODE=TBL3.ORGN_CODE AND TBL1.GRADE=TBL3.GRADE " +
                       "FULL OUTER JOIN (SELECT CURR_ORGN_CODE AS ORGN_CODE,GRADE,COUNT(GPIL_BALE_NUMBER) AS S_CL_BALES,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS S_CL_QTY FROM GPIL_STOCK (NOLOCK) WHERE CROP='" + ddlCrop.Text + "' AND VARIETY='" + ddlVariety.Text + "' AND STATUS ='Y' AND CURR_ORGN_CODE NOT IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC') AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','Y','I','CC') AND D.BALE_TYPE='IPB' AND D.GRADE LIKE '" + ddlCrop.Text + ddlVariety.Text + "%') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GRADE IS NOT NULL  GROUP BY CURR_ORGN_CODE,GRADE ) AS TBL4 ON TBL1.ORGN_CODE=TBL4.ORGN_CODE AND TBL1.GRADE=TBL4.GRADE " +
                       "FULL OUTER JOIN (SELECT ORGN_CODE,GRADE,COUNT(GPIL_BALE_NUMBER) AS S_INT_BALES,ROUND(ISNULL(SUM(MARKED_WT),0),1) AS S_INT_QTY FROM (SELECT (CASE WHEN CURR_ORGN_CODE IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') THEN '#TAP' ELSE CURR_ORGN_CODE END) AS ORGN_CODE,(CASE WHEN CURR_ORGN_CODE IN (SELECT ORGN_CODE FROM GPIL_ORGN_MASTER (NOLOCK) WHERE ORGN_TYPE='TAP') THEN BUYER_GRADE ELSE GRADE END) AS GRADE,GPIL_BALE_NUMBER,MARKED_WT FROM GPIL_STOCK (NOLOCK) WHERE CROP='" + ddlCrop.Text + "' AND VARIETY='" + ddlVariety.Text + "' AND STATUS ='INT' AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N' AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS') AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_1_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC') AND D.BALE_TYPE='OPB' AND D.PRODUCT_TYPE IN ('BP','SLOSS','LOSS')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2 (NOLOCK) D,GPIL_THRESH_RECON_HDR (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS='N'  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "') AND GPIL_BALE_NUMBER NOT IN (SELECT CASE_NUMBER AS GPIL_BALE_NUMBER FROM GPIL_THRESH_RECON_DTLS_2_TEMP (NOLOCK) D,GPIL_THRESH_RECON_HDR_TEMP (NOLOCK) H WHERE H.BATCH_NO=D.BATCH_NO AND H.STATUS IN ('C','CC')  AND H.CROP='" + ddlCrop.Text + "' AND H.VARIETY='" + ddlVariety.Text + "')) AS T1 GROUP BY ORGN_CODE,GRADE ) AS TBL5 ON TBL1.ORGN_CODE=TBL5.ORGN_CODE AND TBL1.GRADE=TBL5.GRADE ORDER BY TBL1.ORGN_CODE,TBL1.GRADE";





                DataTable dt2 = new DataTable();
                dt2 = GLTMgt.GetQueryResult(strsql);
                //SqlCommand command1 = new SqlCommand(strsql, connection);
                //command1.CommandTimeout = 0;
                //SqlDataAdapter adapter1 = new SqlDataAdapter(command1);
                DataTable dtReconciliation1 = new DataTable("DT_GRADEWISE_STOCK");
              //  adapter1.Fill(dtReconciliation1);
                CustomerReport1.Load(Server.MapPath("~/CrystalReport/RptOrgwiseGradewiseStock.rpt"));
                CustomerReport1.SetDataSource(dt2.DefaultView);
              //  CustomerReport1.SetDatabaseLogon(ClsConnection.USRID, ClsConnection.PASSWORD, ClsConnection.SERVERIP, ClsConnection.DBNAME);
                CrystalReportViewer2.ReportSource = CustomerReport1;
                CrystalReportViewer2.DataBind();

               // dt2.dtWeekDtl = dtReconciliation1;
            }
            catch (Exception ex)
            {
                ScriptManager.RegisterStartupScript(this.Page, this.Page.GetType(), "Error", "alert('" + ex.Message.ToString() + "');", true);

            }
        }



        public bool validated()
        {
            if (ddlCrop.SelectedIndex == 0)
            {
                ScriptManager.RegisterStartupScript(this.Page, this.Page.GetType(), "err_msg", "alert('Select Crop Year');", true);
                ddlCrop.Focus();
                return false;
            }
            else if (ddlVariety.SelectedIndex == 0)
            {
                ScriptManager.RegisterStartupScript(this.Page, this.Page.GetType(), "err_msg", "alert('Select Variety');", true);
                ddlVariety.Focus();
                return false;
            }
            else
            {
                return true;
            }
        }
        protected void btnclose_Click(object sender, EventArgs e)
        {

        }
    }
}