//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPILWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GPIL_ITEM_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPIL_ITEM_MASTER()
        {
            this.GPIL_3ROWDATA_DTLS = new HashSet<GPIL_3ROWDATA_DTLS>();
            this.GPIL_3ROWDATA_DTLS1 = new HashSet<GPIL_3ROWDATA_DTLS>();
            this.GPIL_CLASSIFICATION_DTLS = new HashSet<GPIL_CLASSIFICATION_DTLS>();
            this.GPIL_CLASSIFICATION_DTLS_TEMP = new HashSet<GPIL_CLASSIFICATION_DTLS_TEMP>();
            this.GPIL_CROP_TRANS_DTLS = new HashSet<GPIL_CROP_TRANS_DTLS>();
            this.GPIL_CROP_TRANS_DTLS_TEMP = new HashSet<GPIL_CROP_TRANS_DTLS_TEMP>();
            this.GPIL_GRADING_DTLS = new HashSet<GPIL_GRADING_DTLS>();
            this.GPIL_GRADING_DTLS_TEMP = new HashSet<GPIL_GRADING_DTLS_TEMP>();
            this.GPIL_GRADING_HDR = new HashSet<GPIL_GRADING_HDR>();
            this.GPIL_GRADING_HDR_TEMP = new HashSet<GPIL_GRADING_HDR_TEMP>();
            this.GPIL_STOCK = new HashSet<GPIL_STOCK>();
            this.GPIL_STOCK1 = new HashSet<GPIL_STOCK>();
            this.GPIL_SUPP_PURCHS_DTLS = new HashSet<GPIL_SUPP_PURCHS_DTLS>();
            this.GPIL_TAP_FARM_PURCHS_DTLS = new HashSet<GPIL_TAP_FARM_PURCHS_DTLS>();
            this.GPIL_THRESH_RECON_DTLS_1_TEMP = new HashSet<GPIL_THRESH_RECON_DTLS_1_TEMP>();
            this.GPIL_THRESH_RECON_DTLS_2_TEMP = new HashSet<GPIL_THRESH_RECON_DTLS_2_TEMP>();
        }
    
        public int SNO { get; set; }
        [Required(ErrorMessage = "Item Code is required")]
        [StringLength(25, MinimumLength = 6)]
        public string ITEM_CODE { get; set; }
        [Required(ErrorMessage = "Item Group code is required")]
        //[StringLength(25, MinimumLength = 6)]
        public string ITEM_CODE_GROUP { get; set; }
        [Required(ErrorMessage = "Item Group is required")]
        public string ITEM_GROUP { get; set; }
        [Required(ErrorMessage = "Item Type is required")]
        public string ITEM_TYPE { get; set; }
        [Required(ErrorMessage = "Item Descrption is required")]
        public string ITEM_DESC { get; set; }
        [Required(ErrorMessage = "Crop is required")]
        [StringLength(2, MinimumLength = 2)]
        public string CROP { get; set; }
        [Required(ErrorMessage = "Variety is required")]
        [StringLength(2, MinimumLength = 2)]
        public string VARIETY { get; set; }
        [Required(ErrorMessage = "Cost Category is required")]
        [StringLength(25, MinimumLength = 2)]
        public string COST_CATEGORY { get; set; }
        //[Required(ErrorMessage = "Orgn Type is required")]
        public string ORGN_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        [Required(ErrorMessage = "Status is required")]
        public string STATUS { get; set; }
        public string FLAG { get; set; }
        public byte[] LASTUPDATE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        //[Required(ErrorMessage = "Sub-Inventory is required")]
        public string ATTRIBUTE2 { get; set; }
        [Required(ErrorMessage = "BMGL Grade is required")]
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_3ROWDATA_DTLS> GPIL_3ROWDATA_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_3ROWDATA_DTLS> GPIL_3ROWDATA_DTLS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_DTLS> GPIL_CLASSIFICATION_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_DTLS_TEMP> GPIL_CLASSIFICATION_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_DTLS> GPIL_CROP_TRANS_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_DTLS_TEMP> GPIL_CROP_TRANS_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_DTLS> GPIL_GRADING_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_DTLS_TEMP> GPIL_GRADING_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_HDR> GPIL_GRADING_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_HDR_TEMP> GPIL_GRADING_HDR_TEMP { get; set; }
        public virtual GPIL_USER_MASTER GPIL_USER_MASTER { get; set; }
        public virtual GPIL_USER_MASTER GPIL_USER_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_STOCK> GPIL_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_STOCK> GPIL_STOCK1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SUPP_PURCHS_DTLS> GPIL_SUPP_PURCHS_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_TAP_FARM_PURCHS_DTLS> GPIL_TAP_FARM_PURCHS_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_DTLS_1_TEMP> GPIL_THRESH_RECON_DTLS_1_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_DTLS_2_TEMP> GPIL_THRESH_RECON_DTLS_2_TEMP { get; set; }
    }



    //public class ListItemMaster
    //{
    //    public List<GPIL_ITEM_MASTER> ItemMasters { get; set; }
    //}
}
