//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPILWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPIL_CLASSIFICATION_HDR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPIL_CLASSIFICATION_HDR()
        {
            this.GPIL_CLASSIFICATION_DTLS = new HashSet<GPIL_CLASSIFICATION_DTLS>();
        }
    
        public int SNO { get; set; }
        public string BATCH_NO { get; set; }
        public string ORGN_CODE { get; set; }
        public string CLASSIFIER_NAME { get; set; }
        public System.DateTime CLASSIFICATION_DATE { get; set; }
        public string REASONING_CODE { get; set; }
        public string RECIPE_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string STATUS { get; set; }
        public string FLAG { get; set; }
        public byte[] LASTUPDATE { get; set; }
        public string REMARKS { get; set; }
        public string TEMP_REF { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_DTLS> GPIL_CLASSIFICATION_DTLS { get; set; }
        public virtual GPIL_USER_MASTER GPIL_USER_MASTER { get; set; }
        public virtual GPIL_ORGN_MASTER GPIL_ORGN_MASTER { get; set; }
        public virtual GPIL_OPERATION_RECIPE GPIL_OPERATION_RECIPE { get; set; }
    }
}
