//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPILWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPIL_STOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPIL_STOCK()
        {
            this.GPIL_CLASSIFICATION_DTLS = new HashSet<GPIL_CLASSIFICATION_DTLS>();
            this.GPIL_CLASSIFICATION_DTLS_TEMP = new HashSet<GPIL_CLASSIFICATION_DTLS_TEMP>();
            this.GPIL_CROP_TRANS_DTLS = new HashSet<GPIL_CROP_TRANS_DTLS>();
            this.GPIL_CROP_TRANS_DTLS1 = new HashSet<GPIL_CROP_TRANS_DTLS>();
            this.GPIL_CROP_TRANS_DTLS_TEMP = new HashSet<GPIL_CROP_TRANS_DTLS_TEMP>();
            this.GPIL_CROP_TRANS_DTLS_TEMP1 = new HashSet<GPIL_CROP_TRANS_DTLS_TEMP>();
            this.GPIL_GRADING_DTLS = new HashSet<GPIL_GRADING_DTLS>();
            this.GPIL_GRADING_DTLS_TEMP = new HashSet<GPIL_GRADING_DTLS_TEMP>();
            this.GPIL_PROCESS_ORDER_CAPTURE = new HashSet<GPIL_PROCESS_ORDER_CAPTURE>();
            this.GPIL_PROCESS_ORDER_CAPTURE1 = new HashSet<GPIL_PROCESS_ORDER_CAPTURE>();
            this.GPIL_SHIP_MISS = new HashSet<GPIL_SHIP_MISS>();
            this.GPIL_SHIP_MISS1 = new HashSet<GPIL_SHIP_MISS>();
            this.GPIL_SHIPMENT_DTLS = new HashSet<GPIL_SHIPMENT_DTLS>();
            this.GPIL_SHIPMENT_DTLS_TEMP = new HashSet<GPIL_SHIPMENT_DTLS_TEMP>();
            this.GPIL_SO_RESERVATION_DTLS = new HashSet<GPIL_SO_RESERVATION_DTLS>();
            this.GPIL_SO_RESERVATION_DTLS_TEMP = new HashSet<GPIL_SO_RESERVATION_DTLS_TEMP>();
            this.GPIL_THRESH_RECON_DTLS_1 = new HashSet<GPIL_THRESH_RECON_DTLS_1>();
            this.GPIL_THRESH_RECON_DTLS_1_TEMP = new HashSet<GPIL_THRESH_RECON_DTLS_1_TEMP>();
        }
    
        public int SNO { get; set; }
        public string GPIL_BALE_NUMBER { get; set; }
        public string TB_LOT_NO { get; set; }
        public string TBGR_NO { get; set; }
        public string TB_GRADE { get; set; }
        public string BUYER_GRADE { get; set; }
        public string GRADE { get; set; }
        public Nullable<double> MARKED_WT { get; set; }
        public Nullable<double> CURR_WT { get; set; }
        public string ORIGN_LOCN { get; set; }
        public string ORIGN_ORGN_CODE { get; set; }
        public string CURR_LOCN { get; set; }
        public string CURR_ORGN_CODE { get; set; }
        public string CROP { get; set; }
        public string VARIETY { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string SUBINVENTORY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string WEIGHT_FLAG { get; set; }
        public string BALE_CARD_TYPE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string PROCESS_STATUS { get; set; }
        public string BATCH_NO { get; set; }
        public string STATUS { get; set; }
        public string FLAG { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public byte[] LASTUPDATE { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string WMS_STATUS { get; set; }
        public string WMS_FLAG { get; set; }
        public Nullable<int> PICKLIST_NO { get; set; }
        public Nullable<int> LP5NO { get; set; }
        public string NIC { get; set; }
        public string TRS { get; set; }
        public string CL { get; set; }
        public Nullable<System.DateTime> IN_TIME { get; set; }
        public Nullable<System.DateTime> OUT_TIME { get; set; }
        public string FUMIGATION_STATUS { get; set; }
        public Nullable<System.DateTime> FUMIGATION_STARTING_DATE { get; set; }
        public Nullable<System.DateTime> FUMIGATION_ENDING_DATE { get; set; }
        public Nullable<System.DateTime> FUMIGATION_EXPIRY_DATE { get; set; }
        public string FUMIGATED_BY { get; set; }
        public string IS_EXISTING_STOCK { get; set; }
        public string WMS_ATTRIBUTE1 { get; set; }
        public string WMS_ATTRIBUTE2 { get; set; }
        public string WMS_ATTRIBUTE3 { get; set; }
        public string WMS_ATTRIBUTE4 { get; set; }
        public string WMS_ATTRIBUTE5 { get; set; }
        public string WMS_FLAG1 { get; set; }
        public string WMS_FLAG2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_DTLS> GPIL_CLASSIFICATION_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_DTLS_TEMP> GPIL_CLASSIFICATION_DTLS_TEMP { get; set; }
        public virtual GPIL_CROP_MASTER GPIL_CROP_MASTER { get; set; }
        public virtual GPIL_CROP_MASTER GPIL_CROP_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_DTLS> GPIL_CROP_TRANS_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_DTLS> GPIL_CROP_TRANS_DTLS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_DTLS_TEMP> GPIL_CROP_TRANS_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_DTLS_TEMP> GPIL_CROP_TRANS_DTLS_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_DTLS> GPIL_GRADING_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_DTLS_TEMP> GPIL_GRADING_DTLS_TEMP { get; set; }
        public virtual GPIL_ITEM_MASTER GPIL_ITEM_MASTER { get; set; }
        public virtual GPIL_ITEM_MASTER GPIL_ITEM_MASTER1 { get; set; }
        public virtual GPIL_ORGN_MASTER GPIL_ORGN_MASTER { get; set; }
        public virtual GPIL_ORGN_MASTER GPIL_ORGN_MASTER1 { get; set; }
        public virtual GPIL_ORGN_MASTER GPIL_ORGN_MASTER2 { get; set; }
        public virtual GPIL_ORGN_MASTER GPIL_ORGN_MASTER3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_PROCESS_ORDER_CAPTURE> GPIL_PROCESS_ORDER_CAPTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_PROCESS_ORDER_CAPTURE> GPIL_PROCESS_ORDER_CAPTURE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIP_MISS> GPIL_SHIP_MISS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIP_MISS> GPIL_SHIP_MISS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_DTLS> GPIL_SHIPMENT_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_DTLS_TEMP> GPIL_SHIPMENT_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_DTLS> GPIL_SO_RESERVATION_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_DTLS_TEMP> GPIL_SO_RESERVATION_DTLS_TEMP { get; set; }
        public virtual GPIL_VARIETY_MASTER GPIL_VARIETY_MASTER { get; set; }
        public virtual GPIL_VARIETY_MASTER GPIL_VARIETY_MASTER1 { get; set; }
        public virtual GPIL_SUPP_PURCHS_DTLS GPIL_SUPP_PURCHS_DTLS { get; set; }
        public virtual GPIL_TAP_FARM_PURCHS_DTLS GPIL_TAP_FARM_PURCHS_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_DTLS_1> GPIL_THRESH_RECON_DTLS_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_DTLS_1_TEMP> GPIL_THRESH_RECON_DTLS_1_TEMP { get; set; }
    }
}
