//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPILWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class GPIL_USER_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPIL_USER_MASTER()
        {
            this.GPIL_3ROWDATA_DTLS = new HashSet<GPIL_3ROWDATA_DTLS>();
            this.GPIL_3ROWDATA_DTLS1 = new HashSet<GPIL_3ROWDATA_DTLS>();
            this.GPIL_3ROWDATA_HDR = new HashSet<GPIL_3ROWDATA_HDR>();
            this.GPIL_3ROWDATA_HDR1 = new HashSet<GPIL_3ROWDATA_HDR>();
            this.GPIL_3ROWDATA_HDR2 = new HashSet<GPIL_3ROWDATA_HDR>();
            this.GPIL_3ROWDATA_HDR3 = new HashSet<GPIL_3ROWDATA_HDR>();
            this.GPIL_BUYER_VS_CLASSIFIER_GRD_MASTER = new HashSet<GPIL_BUYER_VS_CLASSIFIER_GRD_MASTER>();
            this.GPIL_BUYER_VS_CLASSIFIER_GRD_MASTER1 = new HashSet<GPIL_BUYER_VS_CLASSIFIER_GRD_MASTER>();
            this.GPIL_CLASSIFICATION_DTLS = new HashSet<GPIL_CLASSIFICATION_DTLS>();
            this.GPIL_CLASSIFICATION_DTLS_TEMP = new HashSet<GPIL_CLASSIFICATION_DTLS_TEMP>();
            this.GPIL_CLASSIFICATION_HDR = new HashSet<GPIL_CLASSIFICATION_HDR>();
            this.GPIL_CLASSIFICATION_HDR_TEMP = new HashSet<GPIL_CLASSIFICATION_HDR_TEMP>();
            this.GPIL_CLASSIFICATION_HDR_TEMP1 = new HashSet<GPIL_CLASSIFICATION_HDR_TEMP>();
            this.GPIL_CLASSIFY_SUFFIX = new HashSet<GPIL_CLASSIFY_SUFFIX>();
            this.GPIL_CLASSIFY_SUFFIX1 = new HashSet<GPIL_CLASSIFY_SUFFIX>();
            this.GPIL_CLUSTER_MASTER = new HashSet<GPIL_CLUSTER_MASTER>();
            this.GPIL_CLUSTER_MASTER1 = new HashSet<GPIL_CLUSTER_MASTER>();
            this.GPIL_CLUSTER_MASTER2 = new HashSet<GPIL_CLUSTER_MASTER>();
            this.GPIL_CLUSTER_MASTER3 = new HashSet<GPIL_CLUSTER_MASTER>();
            this.GPIL_COMPANY_MASTER = new HashSet<GPIL_COMPANY_MASTER>();
            this.GPIL_COMPANY_MASTER1 = new HashSet<GPIL_COMPANY_MASTER>();
            this.GPIL_COMPETITION_DTLS = new HashSet<GPIL_COMPETITION_DTLS>();
            this.GPIL_COMPETITION_DTLS1 = new HashSet<GPIL_COMPETITION_DTLS>();
            this.GPIL_COMPETITION_HDR = new HashSet<GPIL_COMPETITION_HDR>();
            this.GPIL_COMPETITION_HDR1 = new HashSet<GPIL_COMPETITION_HDR>();
            this.GPIL_COMPETITION_HDR2 = new HashSet<GPIL_COMPETITION_HDR>();
            this.GPIL_COMPETITION_HDR3 = new HashSet<GPIL_COMPETITION_HDR>();
            this.GPIL_CROP_MASTER = new HashSet<GPIL_CROP_MASTER>();
            this.GPIL_CROP_MASTER1 = new HashSet<GPIL_CROP_MASTER>();
            this.GPIL_CROP_TRANS_DTLS = new HashSet<GPIL_CROP_TRANS_DTLS>();
            this.GPIL_CROP_TRANS_DTLS_TEMP = new HashSet<GPIL_CROP_TRANS_DTLS_TEMP>();
            this.GPIL_CROP_TRANS_HDR = new HashSet<GPIL_CROP_TRANS_HDR>();
            this.GPIL_CROP_TRANS_HDR1 = new HashSet<GPIL_CROP_TRANS_HDR>();
            this.GPIL_CROP_TRANS_HDR_TEMP = new HashSet<GPIL_CROP_TRANS_HDR_TEMP>();
            this.GPIL_CROP_TRANS_HDR_TEMP1 = new HashSet<GPIL_CROP_TRANS_HDR_TEMP>();
            this.GPIL_DAILYSTOCK_BACKUP = new HashSet<GPIL_DAILYSTOCK_BACKUP>();
            this.GPIL_FARMER_FREIGHT_CHARGE_MASTER = new HashSet<GPIL_FARMER_FREIGHT_CHARGE_MASTER>();
            this.GPIL_FARMER_LOAN_TRANSACTIONS = new HashSet<GPIL_FARMER_LOAN_TRANSACTIONS>();
            this.GPIL_FARMER_PURCHASE_TRANSACTIONS = new HashSet<GPIL_FARMER_PURCHASE_TRANSACTIONS>();
            this.GPIL_GRADING_DTLS = new HashSet<GPIL_GRADING_DTLS>();
            this.GPIL_GRADING_DTLS_TEMP = new HashSet<GPIL_GRADING_DTLS_TEMP>();
            this.GPIL_GRADING_HDR = new HashSet<GPIL_GRADING_HDR>();
            this.GPIL_GRADING_HDR1 = new HashSet<GPIL_GRADING_HDR>();
            this.GPIL_GRADING_HDR_TEMP = new HashSet<GPIL_GRADING_HDR_TEMP>();
            this.GPIL_GRADING_HDR_TEMP1 = new HashSet<GPIL_GRADING_HDR_TEMP>();
            this.GPIL_GRADING_NONSUFFIX_ITEM = new HashSet<GPIL_GRADING_NONSUFFIX_ITEM>();
            this.GPIL_GRADING_NONSUFFIX_ITEM1 = new HashSet<GPIL_GRADING_NONSUFFIX_ITEM>();
            this.GPIL_ITEM_MASTER = new HashSet<GPIL_ITEM_MASTER>();
            this.GPIL_ITEM_MASTER1 = new HashSet<GPIL_ITEM_MASTER>();
            this.GPIL_OPERATION_RECIPE = new HashSet<GPIL_OPERATION_RECIPE>();
            this.GPIL_OPERATION_RECIPE1 = new HashSet<GPIL_OPERATION_RECIPE>();
            this.GPIL_ORGN_MASTER = new HashSet<GPIL_ORGN_MASTER>();
            this.GPIL_ORGN_MASTER1 = new HashSet<GPIL_ORGN_MASTER>();
            this.GPIL_SERVICE_CHARGE_INFO = new HashSet<GPIL_SERVICE_CHARGE_INFO>();
            this.GPIL_SERVICE_CHARGE_INFO1 = new HashSet<GPIL_SERVICE_CHARGE_INFO>();
            this.GPIL_SERVICE_CHARGE_MASTER = new HashSet<GPIL_SERVICE_CHARGE_MASTER>();
            this.GPIL_SERVICE_CHARGE_MASTER1 = new HashSet<GPIL_SERVICE_CHARGE_MASTER>();
            this.GPIL_SHIP_MISS = new HashSet<GPIL_SHIP_MISS>();
            this.GPIL_SHIP_MISS1 = new HashSet<GPIL_SHIP_MISS>();
            this.GPIL_SHIPMENT_DTLS = new HashSet<GPIL_SHIPMENT_DTLS>();
            this.GPIL_SHIPMENT_DTLS1 = new HashSet<GPIL_SHIPMENT_DTLS>();
            this.GPIL_SHIPMENT_DTLS_TEMP = new HashSet<GPIL_SHIPMENT_DTLS_TEMP>();
            this.GPIL_SHIPMENT_DTLS_TEMP1 = new HashSet<GPIL_SHIPMENT_DTLS_TEMP>();
            this.GPIL_SHIPMENT_HDR = new HashSet<GPIL_SHIPMENT_HDR>();
            this.GPIL_SHIPMENT_HDR1 = new HashSet<GPIL_SHIPMENT_HDR>();
            this.GPIL_SHIPMENT_HDR2 = new HashSet<GPIL_SHIPMENT_HDR>();
            this.GPIL_SHIPMENT_HDR3 = new HashSet<GPIL_SHIPMENT_HDR>();
            this.GPIL_SHIPMENT_HDR_TEMP = new HashSet<GPIL_SHIPMENT_HDR_TEMP>();
            this.GPIL_SHIPMENT_HDR_TEMP1 = new HashSet<GPIL_SHIPMENT_HDR_TEMP>();
            this.GPIL_SO_RESERVATION_DTLS = new HashSet<GPIL_SO_RESERVATION_DTLS>();
            this.GPIL_SO_RESERVATION_DTLS1 = new HashSet<GPIL_SO_RESERVATION_DTLS>();
            this.GPIL_SO_RESERVATION_DTLS_TEMP = new HashSet<GPIL_SO_RESERVATION_DTLS_TEMP>();
            this.GPIL_SO_RESERVATION_DTLS_TEMP1 = new HashSet<GPIL_SO_RESERVATION_DTLS_TEMP>();
            this.GPIL_SO_RESERVATION_HDR = new HashSet<GPIL_SO_RESERVATION_HDR>();
            this.GPIL_SO_RESERVATION_HDR1 = new HashSet<GPIL_SO_RESERVATION_HDR>();
            this.GPIL_SO_RESERVATION_HDR2 = new HashSet<GPIL_SO_RESERVATION_HDR>();
            this.GPIL_SO_RESERVATION_HDR3 = new HashSet<GPIL_SO_RESERVATION_HDR>();
            this.GPIL_SO_RESERVATION_HDR_TEMP = new HashSet<GPIL_SO_RESERVATION_HDR_TEMP>();
            this.GPIL_SOIL_MASTER = new HashSet<GPIL_SOIL_MASTER>();
            this.GPIL_SOIL_MASTER1 = new HashSet<GPIL_SOIL_MASTER>();
            this.GPIL_SOIL_MASTER2 = new HashSet<GPIL_SOIL_MASTER>();
            this.GPIL_SOIL_MASTER3 = new HashSet<GPIL_SOIL_MASTER>();
            this.GPIL_STACK_MASTER = new HashSet<GPIL_STACK_MASTER>();
            this.GPIL_STACK_MASTER1 = new HashSet<GPIL_STACK_MASTER>();
            this.GPIL_SUBINVENTORY = new HashSet<GPIL_SUBINVENTORY>();
            this.GPIL_SUBINVENTORY1 = new HashSet<GPIL_SUBINVENTORY>();
            this.GPIL_SUPP_PURCHS_DTLS = new HashSet<GPIL_SUPP_PURCHS_DTLS>();
            this.GPIL_SUPP_PURCHS_HDR = new HashSet<GPIL_SUPP_PURCHS_HDR>();
            this.GPIL_SUPP_PURCHS_HDR1 = new HashSet<GPIL_SUPP_PURCHS_HDR>();
            this.GPIL_SUPPLIER_MASTER = new HashSet<GPIL_SUPPLIER_MASTER>();
            this.GPIL_SUPPLIER_MASTER1 = new HashSet<GPIL_SUPPLIER_MASTER>();
            this.GPIL_TAP_FARM_PURCHS_DTLS = new HashSet<GPIL_TAP_FARM_PURCHS_DTLS>();
            this.GPIL_TAP_FARM_PURCHS_HDR = new HashSet<GPIL_TAP_FARM_PURCHS_HDR>();
            this.GPIL_TAP_FARM_PURCHS_HDR1 = new HashSet<GPIL_TAP_FARM_PURCHS_HDR>();
            this.GPIL_THRESH_RECON_DTLS_1 = new HashSet<GPIL_THRESH_RECON_DTLS_1>();
            this.GPIL_THRESH_RECON_DTLS_1_TEMP = new HashSet<GPIL_THRESH_RECON_DTLS_1_TEMP>();
            this.GPIL_THRESH_RECON_DTLS_2 = new HashSet<GPIL_THRESH_RECON_DTLS_2>();
            this.GPIL_THRESH_RECON_DTLS_2_TEMP = new HashSet<GPIL_THRESH_RECON_DTLS_2_TEMP>();
            this.GPIL_THRESH_RECON_HDR = new HashSet<GPIL_THRESH_RECON_HDR>();
            this.GPIL_THRESH_RECON_HDR1 = new HashSet<GPIL_THRESH_RECON_HDR>();
            this.GPIL_THRESH_RECON_HDR_TEMP = new HashSet<GPIL_THRESH_RECON_HDR_TEMP>();
            this.GPIL_THRESH_RECON_HDR_TEMP1 = new HashSet<GPIL_THRESH_RECON_HDR_TEMP>();
            this.GPIL_VARIETY_MASTER = new HashSet<GPIL_VARIETY_MASTER>();
            this.GPIL_VARIETY_SEASON_MASTER = new HashSet<GPIL_VARIETY_SEASON_MASTER>();
            this.GPIL_VARIETY_SEASON_MASTER1 = new HashSet<GPIL_VARIETY_SEASON_MASTER>();
            this.GPIL_VARIETY_MASTER1 = new HashSet<GPIL_VARIETY_MASTER>();
            this.GPIL_VILLAGE_MASTER = new HashSet<GPIL_VILLAGE_MASTER>();
            this.GPIL_VILLAGE_MASTER1 = new HashSet<GPIL_VILLAGE_MASTER>();
        }
    
        public int SNO { get; set; }
        [Required(ErrorMessage = "UserID is required")]
        [StringLength(20, MinimumLength = 4)]
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [StringLength(10, MinimumLength = 4)]
        public string PASSWORD { get; set; }

        //[Display(Name = "Confirm password")]
        //[Required(ErrorMessage = "Please enter confirm password")]
        //[Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]
        //[DataType(DataType.Password)]
        //public string Confirmpwd { get; set; }

        //[Required(ErrorMessage = "Confirmation Password is required.")]
        //[Compare("PASSWORD", ErrorMessage = "Password and Confirmation Password must match.")]
        //public string ConfirmPassword { get; set; }


        //[notmapped] // does not effect with your database
        //[compare("password")]
        //public string confirmpassword { get; set; }

        //[Required(ErrorMessage = "Confirmation Password is required.")]
        //[Compare("PASSWORD", ErrorMessage = "Password and Confirmation Password must match.")]
        //public string CONFRIM_PASSWORD { get; set; }

        public string USER_ERP_NAME { get; set; }
        //[Required(ErrorMessage = "EmpCode is required")]
        public string EMP_CODE { get; set; }
        //[Required(ErrorMessage = "Designation is required")]
        public string DESIGNATION { get; set; }
        //[Required(ErrorMessage = "Department is required")]
        public string DEPARTMENT { get; set; }
        //[Required(ErrorMessage = "UserRights is required")]
        public string USER_RIGHTS { get; set; }
        public string SYNC_ID { get; set; }
        public string SYNC_PASSWORD { get; set; }
        //[Required(ErrorMessage = "MobileNO is required")]
        public string MOBILE_NO { get; set; }
        //[Required(ErrorMessage = "EmailID is required")]
        public string EMAIL_ID { get; set; }

        public string Message { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        //[Required(ErrorMessage = "Status is required")]
        public string STATUS { get; set; }
        public string FLAG { get; set; }
        public byte[] LASTUPDATE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_3ROWDATA_DTLS> GPIL_3ROWDATA_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_3ROWDATA_DTLS> GPIL_3ROWDATA_DTLS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_3ROWDATA_HDR> GPIL_3ROWDATA_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_3ROWDATA_HDR> GPIL_3ROWDATA_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_3ROWDATA_HDR> GPIL_3ROWDATA_HDR2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_3ROWDATA_HDR> GPIL_3ROWDATA_HDR3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_BUYER_VS_CLASSIFIER_GRD_MASTER> GPIL_BUYER_VS_CLASSIFIER_GRD_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_BUYER_VS_CLASSIFIER_GRD_MASTER> GPIL_BUYER_VS_CLASSIFIER_GRD_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_DTLS> GPIL_CLASSIFICATION_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_DTLS_TEMP> GPIL_CLASSIFICATION_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_HDR> GPIL_CLASSIFICATION_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_HDR_TEMP> GPIL_CLASSIFICATION_HDR_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFICATION_HDR_TEMP> GPIL_CLASSIFICATION_HDR_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFY_SUFFIX> GPIL_CLASSIFY_SUFFIX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLASSIFY_SUFFIX> GPIL_CLASSIFY_SUFFIX1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLUSTER_MASTER> GPIL_CLUSTER_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLUSTER_MASTER> GPIL_CLUSTER_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLUSTER_MASTER> GPIL_CLUSTER_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CLUSTER_MASTER> GPIL_CLUSTER_MASTER3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_COMPANY_MASTER> GPIL_COMPANY_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_COMPANY_MASTER> GPIL_COMPANY_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_COMPETITION_DTLS> GPIL_COMPETITION_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_COMPETITION_DTLS> GPIL_COMPETITION_DTLS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_COMPETITION_HDR> GPIL_COMPETITION_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_COMPETITION_HDR> GPIL_COMPETITION_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_COMPETITION_HDR> GPIL_COMPETITION_HDR2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_COMPETITION_HDR> GPIL_COMPETITION_HDR3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_MASTER> GPIL_CROP_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_MASTER> GPIL_CROP_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_DTLS> GPIL_CROP_TRANS_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_DTLS_TEMP> GPIL_CROP_TRANS_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_HDR> GPIL_CROP_TRANS_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_HDR> GPIL_CROP_TRANS_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_HDR_TEMP> GPIL_CROP_TRANS_HDR_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_CROP_TRANS_HDR_TEMP> GPIL_CROP_TRANS_HDR_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_DAILYSTOCK_BACKUP> GPIL_DAILYSTOCK_BACKUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_FARMER_FREIGHT_CHARGE_MASTER> GPIL_FARMER_FREIGHT_CHARGE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_FARMER_LOAN_TRANSACTIONS> GPIL_FARMER_LOAN_TRANSACTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_FARMER_PURCHASE_TRANSACTIONS> GPIL_FARMER_PURCHASE_TRANSACTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_DTLS> GPIL_GRADING_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_DTLS_TEMP> GPIL_GRADING_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_HDR> GPIL_GRADING_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_HDR> GPIL_GRADING_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_HDR_TEMP> GPIL_GRADING_HDR_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_HDR_TEMP> GPIL_GRADING_HDR_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_NONSUFFIX_ITEM> GPIL_GRADING_NONSUFFIX_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_GRADING_NONSUFFIX_ITEM> GPIL_GRADING_NONSUFFIX_ITEM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_ITEM_MASTER> GPIL_ITEM_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_ITEM_MASTER> GPIL_ITEM_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_OPERATION_RECIPE> GPIL_OPERATION_RECIPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_OPERATION_RECIPE> GPIL_OPERATION_RECIPE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_ORGN_MASTER> GPIL_ORGN_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_ORGN_MASTER> GPIL_ORGN_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SERVICE_CHARGE_INFO> GPIL_SERVICE_CHARGE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SERVICE_CHARGE_INFO> GPIL_SERVICE_CHARGE_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SERVICE_CHARGE_MASTER> GPIL_SERVICE_CHARGE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SERVICE_CHARGE_MASTER> GPIL_SERVICE_CHARGE_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIP_MISS> GPIL_SHIP_MISS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIP_MISS> GPIL_SHIP_MISS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_DTLS> GPIL_SHIPMENT_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_DTLS> GPIL_SHIPMENT_DTLS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_DTLS_TEMP> GPIL_SHIPMENT_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_DTLS_TEMP> GPIL_SHIPMENT_DTLS_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_HDR> GPIL_SHIPMENT_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_HDR> GPIL_SHIPMENT_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_HDR> GPIL_SHIPMENT_HDR2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_HDR> GPIL_SHIPMENT_HDR3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_HDR_TEMP> GPIL_SHIPMENT_HDR_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SHIPMENT_HDR_TEMP> GPIL_SHIPMENT_HDR_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_DTLS> GPIL_SO_RESERVATION_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_DTLS> GPIL_SO_RESERVATION_DTLS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_DTLS_TEMP> GPIL_SO_RESERVATION_DTLS_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_DTLS_TEMP> GPIL_SO_RESERVATION_DTLS_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_HDR> GPIL_SO_RESERVATION_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_HDR> GPIL_SO_RESERVATION_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_HDR> GPIL_SO_RESERVATION_HDR2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_HDR> GPIL_SO_RESERVATION_HDR3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SO_RESERVATION_HDR_TEMP> GPIL_SO_RESERVATION_HDR_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SOIL_MASTER> GPIL_SOIL_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SOIL_MASTER> GPIL_SOIL_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SOIL_MASTER> GPIL_SOIL_MASTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SOIL_MASTER> GPIL_SOIL_MASTER3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_STACK_MASTER> GPIL_STACK_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_STACK_MASTER> GPIL_STACK_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SUBINVENTORY> GPIL_SUBINVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SUBINVENTORY> GPIL_SUBINVENTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SUPP_PURCHS_DTLS> GPIL_SUPP_PURCHS_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SUPP_PURCHS_HDR> GPIL_SUPP_PURCHS_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SUPP_PURCHS_HDR> GPIL_SUPP_PURCHS_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SUPPLIER_MASTER> GPIL_SUPPLIER_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_SUPPLIER_MASTER> GPIL_SUPPLIER_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_TAP_FARM_PURCHS_DTLS> GPIL_TAP_FARM_PURCHS_DTLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_TAP_FARM_PURCHS_HDR> GPIL_TAP_FARM_PURCHS_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_TAP_FARM_PURCHS_HDR> GPIL_TAP_FARM_PURCHS_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_DTLS_1> GPIL_THRESH_RECON_DTLS_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_DTLS_1_TEMP> GPIL_THRESH_RECON_DTLS_1_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_DTLS_2> GPIL_THRESH_RECON_DTLS_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_DTLS_2_TEMP> GPIL_THRESH_RECON_DTLS_2_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_HDR> GPIL_THRESH_RECON_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_HDR> GPIL_THRESH_RECON_HDR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_HDR_TEMP> GPIL_THRESH_RECON_HDR_TEMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_THRESH_RECON_HDR_TEMP> GPIL_THRESH_RECON_HDR_TEMP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_VARIETY_MASTER> GPIL_VARIETY_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_VARIETY_SEASON_MASTER> GPIL_VARIETY_SEASON_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_VARIETY_SEASON_MASTER> GPIL_VARIETY_SEASON_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_VARIETY_MASTER> GPIL_VARIETY_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_VILLAGE_MASTER> GPIL_VILLAGE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPIL_VILLAGE_MASTER> GPIL_VILLAGE_MASTER1 { get; set; }
    }

    public class ListUserMaster
    {
        public List<GPIL_USER_MASTER> UserMasters { get; set; }
    }
}
