//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPILWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GPIL_RATE_MASTER
    {
        [Required(ErrorMessage = "LOCATION CODE IS REQUIRED")]
        public string Loc_Code { get; set; }
        [Required(ErrorMessage = "ITEM CODE IS REQUIRED")]
        public string Item_Code { get; set; }
        [Required(ErrorMessage = "RATE IS REQUIRED")]
        public decimal Rate { get; set; }
        
        public System.DateTime Last_Updated_Date { get; set; }
    }
}
