//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPILWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_TRANSACTION_LOG
    {
        public string GLOBAL_TRAN_ID { get; set; }
        public string TRAN_COMMENT { get; set; }
    }
}
