//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPILWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDispatchDetail
    {
        public string LocCode { get; set; }
        public int PickListNo { get; set; }
        public int LP5No { get; set; }
        public string LRNo { get; set; }
        public Nullable<System.DateTime> LRDate { get; set; }
        public string AWBNo { get; set; }
        public string TransporterCode { get; set; }
        public string TruckNo { get; set; }
        public string ToLocCode { get; set; }
        public string FreightWeight { get; set; }
        public Nullable<bool> IsLP5Note { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DispatchedOn { get; set; }
        public string DispatchedBy { get; set; }
        public Nullable<byte> D_Stts { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual mTransporter mTransporter { get; set; }
        public virtual tDispatchNote tDispatchNote { get; set; }
    }
}
